name: Release

on:
    push:
        branches:
          - release

env:
    GH_TOKEN: ${{ secrets.GH_TOKEN }}
    GIT_AUTHOR_EMAIL: ${{ secrets.GIT_AUTHOR_EMAIL }}
    GIT_AUTHOR_NAME: ${{ secrets.GIT_AUTHOR_NAME }}
    NODE_VERSION: 16

jobs:
    release:
        name: Release
        runs-on: windows-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v2

          - name: Setup Node v${{ env.NODE_VERSION }}
            uses: actions/setup-node@v2
            with:
                node-version: ${{ env.NODE_VERSION }}
                cache: 'yarn'

          - name: Install dependencies
            run: yarn --frozen-lockfile --non-interactive --network-timeout 300000

          - name: semantic-release
            run: yarn semantic-release
